spring.application.name=home

# DataSource Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ssafy_home?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
spring.datasource.username=ssafy
spring.datasource.password=ssafy

# MyBatis Configuration
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.ssafy.home.dto
mybatis.configuration.map-underscore-to-camel-case=true

# Server Configuration
server.port=8080


# Springdoc (OpenAPI/Swagger) Configuration

# Specifies the path to access the generated OpenAPI 3.0 document (JSON/YAML).
springdoc.api-docs.path=/api-docs
# Specifies the path to access the Swagger UI web interface.
springdoc.swagger-ui.path=/swagger

# Sorting Order Settings
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

# Specifies whether to include the Spring Boot Actuator endpoints (/health, /info, etc.) in the documentation.
springdoc.show-actuator=true
# Specifies the base package where controller classes are located for API documentation generation.
springdoc.packages-to-scan=com.ssafy.home.controller